### ISSUE TITLE
Could not Publish to Server - Generates "Not Direct Child" Error 

### ISSUE THREAD

**Issue by jpmc216** [adobe/aem-eclipse-developer-tools#63]
When I try to add a AEM 6.1 content project to server (Eclipse Mars), this is the error I get. 

*_Could not publish to the server. Resource at path  /apps/test/components/image/analytics is not a direct child of /apps/test/components/image/tab_properties. *_

If i ignore this error and go ahead and make any changes under "/apps", this is the error i get. 

**Failed publishing path=/apps, result=JcrResult[ success:false, exception: org.apache.sling.ide.transport.RepositoryException - javax.jcr.nodetype.ConstraintViolationException: Item is protected]**

I am using the latest Sling IDE tooling (1.0.10) from the below link. 
https://sling.apache.org/downloads.cgi#ide-tooling

**Comment by rombert** [comment]
Thanks for the report. Can you upload a minimal content package which reproduces the 'not direct child' problem?

**Comment by jpmc216** [comment]
Rombert,

Our project folder structure is little different. So even though I am able to add this as content project, I am not able to see changes getting reflected. 

I also created Linked Folder (jcr_root) to point to webapp folder. That didnt work as well. 

![image](https://cloud.githubusercontent.com/assets/14977933/13056000/8a432080-d3e0-11e5-8a42-d1b88c85c135.png)

**Comment by rombert** [comment]
How is your project structure different? Can you describe your project layout?

**Comment by jpmc216** [comment]
Project layout looks this. 

![image](https://cloud.githubusercontent.com/assets/14977933/13076339/aac884b8-d47f-11e5-931a-3084251ed882.png)

1. We do not have "jcr_root" folder, used "webapp" folder for that. 
2. filter.xml is under this folder "src/main/resources/META-INF/vault/"


Because I was not able to add "app" part of the project as content project, I created a dummy folder with name "content' and added couple of "Linked Folder(s)" one for "jcr_root" and other for "META-INF". 

![image](https://cloud.githubusercontent.com/assets/14977933/13076599/40c7c9fa-d481-11e5-9fad-c5f7c1c378fc.png)


After creating the linked folders, when i try to add "app" as content project this is how it looks. 

![image](https://cloud.githubusercontent.com/assets/14977933/13076632/842db2cc-d481-11e5-9028-ca7a3d073f06.png)

Trying to add the resource to the server. 
![image](https://cloud.githubusercontent.com/assets/14977933/13076648/a1e8adee-d481-11e5-9ba5-73473e0e470c.png)

This is what I see after I click on "Finish", 
![image](https://cloud.githubusercontent.com/assets/14977933/13076672/d651b486-d481-11e5-9666-f51071cc7bad.png)


![image](https://cloud.githubusercontent.com/assets/14977933/13076679/ea0bfdf6-d481-11e5-9183-ca8f3a2d0588.png)


The java (core) bundle part of working perfectly fine, but not the "app" (content) part.

**Comment by rombert** [comment]
I have set up a folder structure similar to the one you described, and with a simple project sync works as expected ( see screenshot below )

![eclipse-sling-linked-folder](https://cloud.githubusercontent.com/assets/21237/13078234/5b5798c8-d4c6-11e5-8962-40b4624db44e.jpeg)

Not sure what exactly is going on in your case, but I'd need a simplified project to make progress on discovering the root cause.

**Comment by jpmc216** [comment]
Rombert,

I have uploaded test image component which is causing issues. Can you try adding to the same project and test your changes. 

[sample-component.zip](https://github.com/Adobe-Marketing-Cloud/aem-eclipse-developer-tools/files/139574/sample-component.zip)

**Comment by jpmc216** [comment]
Additional Information

1. Our project is set up based on AEM 6.1. 
2. After modifying /apps as nt:folder rather than sling:Folder, I bypassed though the below error. 
https://github.com/Adobe-Marketing-Cloud/aem-eclipse-developer-tools/issues/1    and I am able to see "JCR Properties" for all nodes now.
3. But I am still unable to sync the files and folders. I get the below error. 

![image](https://cloud.githubusercontent.com/assets/14977933/13207040/c7f5edee-d8d7-11e5-8995-fedfef6da96c.png)

![image](https://cloud.githubusercontent.com/assets/14977933/13207050/f94a718a-d8d7-11e5-92ab-35f1112e763d.png)

**Comment by eglistefan** [comment]
@jpmc216 this looks like /apps is not part of the filter.xml - check the filter.xml file under src/main/content/META-INF

**Comment by jpmc216** [comment]
filter.xml looks like this.

![image](https://cloud.githubusercontent.com/assets/14977933/13215632/d53ef07a-d924-11e5-8ef9-ed1e9ca30d0c.png)

**Comment by eglistefan** [comment]
> We do not have "jcr_root" folder, used "webapp" folder for that. 
perhaps that's the problem - does it work when you call it jcr_root?

**Comment by jpmc216** [comment]
I have created a linked folder "jcr_root" pointing to webapp. That should work as well right? 

![image](https://cloud.githubusercontent.com/assets/14977933/13216032/63474686-d927-11e5-8f98-f4402a688753.png)

**Comment by eglistefan** [comment]
Perhaps try without linking (but moving the content under jcr_root) - if that works and linking not, then we'd have narrowed down the problem

**Comment by jpmc216** [comment]
Created folders rather than linked folders and this is the error I get. 

java.lang.IllegalArgumentException: Resource at path /apps/test/components/image/analytics is not a direct child of /apps/test/components/image/tab_properties
at org.apache.sling.ide.transport.ResourceProxy.addChild(ResourceProxy.java:62)
	at org.apache.sling.ide.eclipse.core.internal.ResourceChangeCommandFactory.normaliseResourceChildren(ResourceChangeCommandFactory.java:492)
	at org.apache.sling.ide.eclipse.core.internal.ResourceChangeCommandFactory.buildResourceAndInfo(ResourceChangeCommandFactory.java:154)
	at org.apache.sling.ide.eclipse.core.internal.ResourceChangeCommandFactory.addFileCommand(ResourceChangeCommandFactory.java:90)
	at org.apache.sling.ide.eclipse.core.internal.ResourceChangeCommandFactory.newCommandForAddedOrUpdated(ResourceChangeCommandFactory.java:81)
	at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.addFileCommand(SlingLaunchpadBehaviour.java:554)
	at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishContentModule(SlingLaunchpadBehaviour.java:420)
	at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishModule(SlingLaunchpadBehaviour.java:228)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1091)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1183)
	at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:137)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
	at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:54)
	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3172)
	at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:345)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by rombert** [comment]
I have tested the image component that you attached and it works fine for me ... I am using the latest trunk version, but there have been no changes which are relevant to this scenario.

It's a shot in the dark, but can you gather the Eclipse trace logs as decribed at https://sling.apache.org/documentation/development/ide-tooling.html#gathering-debug-information ? Please enable all 'Sling IDE Tooling' tracers, save them to a log file and attach them to this ticket ( feel free to mail me directly if the log contains sensitive information ).

Thanks!

**Comment by paul-bjorkstrand** [comment]
I have run into this in the past, and yesterday ran into it again (I forgot how exactly I fixed it last time). After debugging the Sling eclipse plugin itself, I stumbled upon how I solved the issue before.

When using the Sling IDE Tools (which AEM Eclipse Developer Tools uses and depends upon), it seems that one cannot have an arbitrarily named xml file that contains arbitrary nodes. This works when built into a package, but not with the plugin.

Our problem was originally with the `cq:dialog` nodes. Having _cq_dialog.xml files in the components' folders caused this error. To fix it, we did the following:

1. Create a folder with the node name, in our case `_cq_dialog` which is the mangled name for `cq:dialog`.
2. Move the original xml file into previously creaded folder, giving us the structure `_cq_dialog/_cq_dialog.xml`
3. Rename the xml file to `.content.xml`.
4. Profit!

I have not tried this for your example, but I imagine this method is extensible to your situation.

Hope this helps.

Cheers!

**Comment by vikrave** [comment]
Hi Paul

     I am also facing the same issue. I tried pauls solution and is not working . Does anyone have any solution ?

Thanks
Veena

**Comment by pulichintala** [comment]
i am trying to change jcr:primaryType of a new node under ui.content  and when i try to publish my changes i get this error

![eclipse](https://user-images.githubusercontent.com/28933873/36675675-125de73c-1ae0-11e8-8e1f-84a4e6a27fab.PNG)

**Comment by eglistefan** [comment]
I think the problem is that you're automatically publishing the changes and that node existed previously with a different jcr:primaryType. Try manually removing the original node with CRXDE and republishing.

**Comment by pulichintala** [comment]
@eglistefan i tried that as well did not help, even tried deleting ui.content folder and re-publishing and also i installed the new content package as well, still getting the same error.

**Comment by eglistefan** [comment]
have you tried with a different node, eg /foo/bar?

**Comment by pulichintala** [comment]
@eglistefan  deleting the main folder rather than a node and republishing fixed it.
Thank you.

**Comment by not-entirely-random** [comment]
I consistently have this problem using AEM archetype 15 in Eclipse in Windows. AEM 6.4
Works fine until I reboot my VM and fails to deploy afterwards.
It cost me a lot of hours to figure this out, so "you are welcome" if my post helps you!

The following set of steps resolve the issue for me (until next reboot):
1. Disconnect from AEM instance in server pane

2. Disable automatic build

3. Select all projects - select Clean -> let Eclipse finish

4. Select All projects -> Maven -> Update Maven project.
**Ensure "Refresh Workspace Resources from local filesystem" is DISABLED / not checked.** 
Click "OK"
Let Eclipse finish

5. Project -> Build All

6. Connect to AEM instance in debug mode in Servers Page

8. Select "Clean and Publish" in Servers Pane

9. Live a happy live

**Comment by timdonovanuk** [comment]
Thanks @not-entirely-random! I was getting this with the WKND tutorial. Following your steps fixed it.
